name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches: [main]
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@4eb9f110bac952a8b68ecf92e3b5c7a987594ba6 # v1.292.0
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Build Jekyll site
        run: |
          bundle exec jekyll build
          touch _site/.nojekyll
        env:
          JEKYLL_ENV: production
          PAGES_REPO_NWO: ${{ github.repository }}

      - name: Test site
        run: |
          bundle exec htmlproofer _site \
            \-\-disable-external \
            \-\-ignore-urls "/^http:\/\/127.0.0.1/,/^http:\/\/0.0.0.0/,/^http:\/\/localhost/"

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          branch: gh-pages
          folder: _site
          clean-exclude: pr-preview
